/*
 * Copyright (c) 2022-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export {
  AttributeModifier,
  ContentModifier,
  CustomStyles,
  GestureModifier,
  UIGestureEvent,
  DrawModifier,
  LayoutSafeAreaType,
  TouchResult,
  TouchTestInfo,
  LayoutSafeAreaEdge,
  ResponseRegion
} from "./component/common";
export * from "./component/gesture";
export * from "./component/customComponentLifecycle";
export {
  LifeCycle,
  ExtendableComponent,
} from "./component/extendableComponent";
export {
  CustomDialogControllerOptions,
  CustomDialogController,
} from "./component/customDialogController";
export { WrappedBuilder } from "./component/builder";
export {
  BaseCustomComponent,
  CustomComponent,
  CustomComponentV2,
  CustomComponentLifecycleState,
  CustomComponentLifecycleObserver,
  CustomComponentLifecycle,
  LifeCycleEvent,
} from "./component/customComponent";

export { AttributeUpdater } from "./AttributeUpdater";
export { LocalStorage } from "./stateManagement"

export * from "./extractors";
export * from "./hooks"

export {
  ArkUIExtensionComponentPeerBase
} from "./component/uiExtensionComponent"
export * from "./component/initializers"
export * from "./component/securityUIExtensionComponent"
export * from "./component/common"
export * from "./component/canvas"
export * from "./component/waterFlow"
export * from "./component/embeddedComponent"
export * from "./component/nodeContainer"
