/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import router from '@ohos.router';

interface ListCategories {
  title:string,
  utl:string
}

@Entry
@Component
struct Index5_2 {
  @State message: string = 'Search'
  private items : ListCategories[] = [
    {title:'radius Dimension类型',utl:'pages/6-1/Text'},
    {title:'radius BorderRadiuses类型',utl:'pages/6-1/Text1'},
    {title:'不设置color和radius',utl:'pages/6-1/Text2'},
    {title:'ContainerSpan包含ImageSpan、Span',utl:'pages/6-1/Text3'},
    {title:'ContainerSpan包含多个子组件，只设置其中一个背景色',utl:'pages/6-1/Text4'},
    {title:'ContainerSpan包含多个子组件，都设置textBackgroundStyle',utl:'pages/6-1/Text5'},
  ]

  build() {
    Column() {
      List({space:'10vp'}) {
        ForEach(this.items,(item : ListCategories) => {
          ListItem() {
            Text(item.title).fontSize(16).fontWeight(FontWeight.Bold).onClick(() => {
              router.pushUrl({url:item.utl})
            })
          }.width('90%').height('40vp').backgroundColor('#ff53ecd9').borderRadius(10)
        })
      }.alignListItem(ListItemAlign.Center).margin({top:'10vp'}).width('100%').height('90%')
    }.width('100%').height('100%')
  }
}