/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { NavList, NavListItem } from '../../utils/navigationList'

@Builder
export function SliderIndexBuilder(name: string, param: Object) {
  SliderIndex()
}

@Entry
@Component
export struct SliderIndex {
  pathStack: NavPathStack = new NavPathStack()
  paths: NavListItem[] = [
    { name: 'SliderStyle', path: 'SliderStyle' },
    { name: 'SliderBlockStyle', path: 'SliderBlockStyle' },
    { name: 'SliderCustom', path: 'SliderCustom' },
    { name: 'SliderTips', path: 'SliderTips' },
    { name: 'SliderNormal', path: 'SliderNormal' },
    { name: 'SliderLevel0', path: 'SliderLevel0' },
    { name: 'SliderLevel01', path: 'SliderLevel01' },
    { name: 'SliderLevel10', path: 'SliderLevel10' },
    { name: 'SliderLevel11', path: 'SliderLevel11' },
    { name: 'SliderLevel12', path: 'SliderLevel12' },
    { name: 'SliderLevel13', path: 'SliderLevel13' },
    { name: 'SliderLevel14', path: 'SliderLevel14' },
    { name: 'SliderLevel15', path: 'SliderLevel15' },
    { name: 'SliderPrefixSuffix', path: 'SliderPrefixSuffix' },
    { name: 'SliderShowSteps', path: 'SliderShowSteps' },
    { name: 'SliderBlockColor', path: 'SliderBlockColor' },
    { name: 'Slider组合场景16', path: 'SliderLevel16' },
    { name: 'SliderTrackColorMetrics', path: 'SliderTrackColorMetrics' }
  ]

  build() {
    NavDestination() {
      NavList({
        pages: this.paths,
        onPathChange: (item: NavListItem) => {
          this.pathStack.pushPath({ name: item.path })
        }
      })
    }
    .title('Slider')
    .onBackPressed(() => {
      this.pathStack.pop()
      return true
    })
    .onReady((context: NavDestinationContext) => {
      this.pathStack = context.pathStack;
    })
  }
}