/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { ComponentBase } from "./../ComponentBase";
import { AccessibilityCallback, AccessibilityRoleType, AlignRuleOption, AnimatableArithmetic, AnimateParam, AttributeModifier } from '../component/common';
import { Bindable, BackgroundBlurStyleOptions, BackgroundBrightnessOptions, BackgroundEffectOptions, BlendApplyType } from '../component/common';
import { BlurOptions, BlurStyle, BorderImageOption, ChainStyle, ClickEffect, ClickEvent, CommonAttribute, ContentCoverOptions } from '../component/common';
import { ContextMenuOptions, CustomPopupOptions, DragEvent, DragInteractionOptions, DragItemInfo } from '../component/common';
import { CustomBuilder } from '../framework';
import { DragPreviewOptions, DrawModifier, EffectType, ForegroundBlurStyleOptions, ForegroundEffectOptions } from '../component/common';
import { GeometryTransitionOptions, GestureModifier, GestureRecognizerJudgeBeginCallback, HoverEvent, InvertOptions, KeyEvent } from '../component/common';
import { LinearGradientBlurOptions, BackgroundOptions } from '../component/common';
import { LocalizedAlignRuleOptions, MenuElement, MenuOptions, ModalTransition, MotionBlurOptions, MotionPathOptions } from '../component/common';
import { MouseEvent, OutlineStyle, OverlayOptions, PixelRoundPolicy, PixelStretchEffectOptions, PopupOptions, PreDragStatus } from '../component/common';
import { ProgressMask, Rectangle, ResponseRegion, RotateOptions, SafeAreaEdge, SafeAreaType, ScaleOptions, ShadowOptions, ShadowStyle } from '../component/common';
import { SheetOptions, ShouldBuiltInRecognizerParallelWithCallback, SizeChangeCallback, StateStyles, TouchEvent, TouchResult } from '../component/common';
import { TouchTestInfo, TouchTestDoneCallback, TransitionEffect, TransitionFinishCallback, TranslateOptions } from '../component/common';
import { VisibleAreaChangeCallback, sharedTransitionOptions, BackgroundImageOptions, ArkCommonMethodPeer } from '../component/common';
import { SystemAdaptiveOptions, CrownEvent, FocusAxisEvent, AxisEvent, FocusMovement, LinearGradientOptions } from '../component/common';
import { OnDragEventCallback, LayoutPolicy, PreviewConfiguration, DropOptions, SweepGradientOptions, AccessibilitySamePageMode } from '../component/common';
import { AccessibilityFocusCallback, ReuseOptions, TipsMessageType, TipsOptions, VisibleAreaEventOptions, RadialGradientOptions} from '../component/common';
import { Color, HitTestMode, ImageSize, Alignment, BorderStyle, ColoringStrategy, HoverEffect, Visibility, ItemAlign, Direction, ObscuredReasons, RenderFit, FocusDrawLevel, ImageRepeat, RenderStrategy, Axis, ResponseType, FunctionKey, ModifierKey } from '../component/enums'
import { ResourceColor, ConstraintSizeOptions, SizeOptions, Length, ChainWeightOptions, Padding, LocalizedPadding, Position, BorderOptions, EdgeWidths, LocalizedEdgeWidths, EdgeColors, LocalizedEdgeColors, BorderRadiuses, LocalizedBorderRadiuses, OutlineOptions, EdgeOutlineStyles, Dimension, EdgeOutlineWidths, OutlineRadiuses, Area, LocalizedEdges, LocalizedPosition, ResourceStr, AccessibilityOptions, EdgeStyles, Edges } from '../component/units'
import { Resource } from "global.resource"
import { LengthMetrics } from "../Graphics"
import {  PixelMap, UniformDataType } from "#external"
import { ResizableOptions } from "../component/image"
import { Filter, VisualEffect, BrightnessBlender } from "#external"
import { CircleShape, EllipseShape, PathShape, RectShape } from "@ohos.arkui.shape"
import { FocusBoxStyle, FocusPriority } from "../component/focus"
import { GestureInfo, BaseGestureEvent, GestureJudgeResult, GestureType, GestureMask } from "../component/gesture"
import { ComponentContent } from 'arkui/ComponentContent'
import { BlendMode } from "../component/common"
import { InteropNativeModule } from '@koalaui/interop';
import { ArkUIAniModule } from 'arkui.ani';
import { hookCustomPropertyImpl, hookAllowDrop, hookDragPreviewOptions } from '#handwritten';
import { CustomProperty } from '#generated';
import { dragController } from "@ohos.arkui.dragController"
import { SpringLoadingContext, DragSpringLoadingConfiguration } from '#generated';

export class ArkBaseNode extends ComponentBase implements CommonAttribute {

    constructParam(...param: Object[]): this {
        return this;
    }
    markDirty(): void {
        ArkUIAniModule._FrameNode_MarkDirtyNode(this.getPeer().getPeerPtr());
        return;
    }
    initialize(...args: Object[]): this {
        return this;
    }
    allowChildCount(): number {
        return -1;
    }
    allowChildTypes(): string[] | undefined {
        return undefined;
    }
    getPeer(): ArkCommonMethodPeer {
        return this.peer as ArkCommonMethodPeer;
    }
    public drawModifier(value: DrawModifier | undefined): this {
        return this
    }
    public responseRegion(value: Array<Rectangle> | Rectangle | undefined): this {
        this.getPeer().setResponseRegionAttribute(value);
        return this
    }
    public mouseResponseRegion(value: Array<Rectangle> | Rectangle | undefined): this {
        return this
    }
    public responseRegionList(value: Array<ResponseRegion> | undefined): this {
        this.getPeer().setResponseRegionListAttribute(value);
        return this
    }

    public constraintSize(value: ConstraintSizeOptions | undefined): this {
        this.getPeer().setConstraintSizeAttribute(value);
        return this
    }
    public touchable(value: boolean | undefined): this {
        return this
    }
    public hitTestBehavior(value: HitTestMode | undefined): this {
        this.getPeer().setHitTestBehaviorAttribute(value);
        return this
    }
    public onChildTouchTest(value: ((value: Array<TouchTestInfo>) => TouchResult) | undefined): this {
        return this
    }
    public layoutWeight(value: number | string | undefined): this {
        this.getPeer().setLayoutWeightAttribute(value);
        return this
    }
    public chainWeight(value: ChainWeightOptions | undefined): this {
        this.getPeer().setChainWeightAttribute(value);
        return this
    }
    public padding(value: Padding | Length | LocalizedPadding | undefined): this {
        this.getPeer().setPaddingAttribute(value);
        return this
    }
    public safeAreaPadding(value: Padding | LengthMetrics | LocalizedPadding | undefined): this {
        this.getPeer().setSafeAreaPaddingAttribute(value);
        return this
    }
    public margin(value: Padding | Length | LocalizedPadding | undefined): this {
        this.getPeer().setMarginAttribute(value);
        return this
    }
    public pixelRound(value: PixelRoundPolicy | undefined): this {
        this.getPeer().setPixelRoundAttribute(value);
        return this
    }
    public backgroundImageSize(value: SizeOptions | ImageSize | undefined): this {
        this.getPeer().setBackgroundImageSizeAttribute(value);
        return this
    }
    public backgroundImagePosition(value: Position | Alignment | undefined): this {
        this.getPeer().setBackgroundImagePositionAttribute(value);
        return this
    }
    public backgroundEffect(options: BackgroundEffectOptions | undefined, sysOptions?: SystemAdaptiveOptions): this {
        return this
    }
    public backgroundImageResizable(value: ResizableOptions | undefined): this {
        this.getPeer().setBackgroundImageResizableAttribute(value);
        return this
    }
    public foregroundEffect(value: ForegroundEffectOptions | undefined): this {
        return this
    }
    public visualEffect(value: VisualEffect | undefined): this {
        return this
    }
    public backgroundFilter(value: Filter | undefined): this {
        return this
    }
    public foregroundFilter(value: Filter | undefined): this {
        return this
    }
    public compositingFilter(value: Filter | undefined): this {
        return this
    }
    public opacity(value: number | Resource | undefined): this {
         if (value != null) {
            this.getPeer().setOpacityAttribute(value);
        }
        return this;
    }
    public border(value: BorderOptions | undefined): this {
        this.getPeer().setBorderAttribute(value);
        return this
    }
    public borderStyle(value: BorderStyle | EdgeStyles | undefined): this {
        return this
    }
    public borderWidth(value: Length | EdgeWidths | LocalizedEdgeWidths | undefined): this {
        if (value != null) {
            this.getPeer().setBorderWidthAttribute(value);
        }
        return this;
    }
    public borderColor(value: ResourceColor | EdgeColors | LocalizedEdgeColors | undefined): this {
        this.getPeer().setBorderColorAttribute(value);
        return this
    }
    public borderRadius(value: Length | BorderRadiuses | LocalizedBorderRadiuses | undefined, type?: RenderStrategy): this {
        this.getPeer().setBorderRadiusAttribute(value, type);
        return this
    }
    public borderImage(value: BorderImageOption | undefined): this {
        this.getPeer().setBorderImageAttribute(value);
        return this
    }
    public outline(value: OutlineOptions | undefined): this {
        return this
    }
    public outlineStyle(value: OutlineStyle | EdgeOutlineStyles | undefined): this {
        return this
    }
    public outlineWidth(value: Dimension | EdgeOutlineWidths | undefined): this {
        return this
    }
    public outlineColor(value: ResourceColor | EdgeColors | LocalizedEdgeColors | undefined): this {
        return this
    }
    public outlineRadius(value: Dimension | OutlineRadiuses | undefined): this {
        return this
    }
    public foregroundColor(value: ResourceColor | ColoringStrategy | undefined): this {
        return this
    }
    public onHover(value: ((isHover: boolean, event: HoverEvent) => void) | undefined): this {
        this.getPeer().setOnHoverAttribute(value);
        return this
    }
    public onHoverMove(value: ((parameter: HoverEvent) => void) | undefined): this {
        this.getPeer().setOnHoverMoveAttribute(value);
        return this
    }
    public onAccessibilityHover(value: AccessibilityCallback | undefined): this {
        return this
    }
    public hoverEffect(value: HoverEffect | undefined): this {
        this.getPeer().setHoverEffectAttribute(value);
        return this
    }
    public onMouse(value: ((event: MouseEvent) => void) | undefined): this {
        this.getPeer().setOnMouseAttribute(value);
        return this
    }
    public onTouch(value: ((event: TouchEvent) => void) | undefined): this {
        this.getPeer().setOnTouchAttribute(value);
        return this
    }
    public onTouchTestDone(value: TouchTestDoneCallback | undefined): this {
        this.getPeer().setOnTouchTestDoneAttribute(value);
        return this
    }
    public onKeyEvent(value: ((parameter: KeyEvent) => boolean) | undefined): this {
        this.getPeer().setOnKeyEventAttribute(value);
        return this
    }
    public onDigitalCrown(value: ((parameter: CrownEvent) => void) | undefined): this {
        return this
    }
    public onKeyPreIme(value: ((parameter: KeyEvent) => boolean) | undefined): this {
        this.getPeer().setOnKeyPreImeAttribute(value);
        return this
    }
    public onKeyEventDispatch(value: ((parameter: KeyEvent) => boolean) | undefined): this {
        this.getPeer().setOnKeyEventDispatchAttribute(value);
        return this
    }
    public onFocusAxisEvent(value: ((parameter: FocusAxisEvent) => void) | undefined): this {
        this.getPeer().setOnFocusAxisEventAttribute(value);
        return this
    }
    public onAxisEvent(value: ((parameter: AxisEvent) => void) | undefined): this {
        this.getPeer().setOnAxisEventAttribute(value);
        return this
    }
    public focusable(value: boolean | undefined): this {
        this.getPeer().setFocusableAttribute(value);
        return this
    }
    public nextFocus(value: FocusMovement | undefined): this {
        this.getPeer().setNextFocusAttribute(value);
        return this
    }
    public tabStop(value: boolean | undefined): this {
        this.getPeer().setTabStopAttribute(value);
        return this
    }
    public onFocus(value: (() => void) | undefined): this {
        this.getPeer().setOnFocusAttribute(value);
        return this
    }
    public onBlur(value: (() => void) | undefined): this {
        this.getPeer().setOnBlurAttribute(value);
        return this
    }
    public tabIndex(value: int | undefined): this {
        this.getPeer().setTabIndexAttribute(value);
        return this
    }
    public defaultFocus(value: boolean | undefined): this {
        this.getPeer().setDefaultFocusAttribute(value);
        return this
    }
    public groupDefaultFocus(value: boolean | undefined): this {
        this.getPeer().setDefaultFocusAttribute(value);
        return this
    }
    public focusOnTouch(value: boolean | undefined): this {
        this.getPeer().setFocusOnTouchAttribute(value);
        return this
    }
    public focusBox(value: FocusBoxStyle | undefined): this {
        this.getPeer().setFocusBoxAttribute(value);
        return this
    }
    public animationStart(value: AnimateParam | undefined): this {
        return this
    }
    public __createOrSetAnimatableProperty<T>(functionName: string, value: number | AnimatableArithmetic<T>,
        callback: (value: number | AnimatableArithmetic<T>) => void): void {}
    public animationStop(value: AnimateParam | undefined): this {
        return this
    }
    public animation(value: AnimateParam | undefined): this {
        return this
    }
    public transition(value: TransitionEffect | undefined): this {
        return this
    }
    public motionBlur(value: MotionBlurOptions | undefined): this {
        return this
    }
    public brightness(value: number | undefined): this {
        return this
    }
    public contrast(value: number | undefined): this {
        return this
    }
    public grayscale(value: number | undefined): this {
        return this
    }
    public colorBlend(value: Color | string | Resource | undefined): this {
        return this
    }
    public saturate(value: number | undefined): this {
        return this
    }
    public sepia(value: number | undefined): this {
        return this
    }
    public invert(value: number | InvertOptions | undefined): this {
        return this
    }
    public hueRotate(value: number | string | undefined): this {
        return this
    }
    public useShadowBatching(value: boolean | undefined): this {
        return this
    }
    public useEffect(useEffect: boolean | undefined, effectType?: EffectType | undefined | EffectType): this {
        return this
    }
    public renderGroup(value: boolean | undefined): this {
        return this
    }
    public freeze(value: boolean | undefined): this {
        return this
    }
    public translate(value: TranslateOptions | undefined): this {
        return this
    }
    public scale(value: ScaleOptions | undefined): this {
        return this
    }
    public gridSpan(value: number | undefined): this {
        return this
    }
    public gridOffset(value: number | undefined): this {
        return this
    }
    public rotate(value: RotateOptions | undefined): this {
        return this
    }
    public transform(value: Object | undefined): this {
        return this
    }
    public onAppear(value: (() => void) | undefined): this {
        this.getPeer().setOnAppearAttribute(value);
        return this
    }
    public onDisAppear(value: (() => void) | undefined): this {
        this.getPeer().setOnDisAppearAttribute(value);
        return this
    }
    public onAttach(value: (() => void) | undefined): this {
        this.getPeer().setOnAttachAttribute(value);
        return this
    }
    public onDetach(value: (() => void) | undefined): this {
        this.getPeer().setOnDetachAttribute(value);
        return this
    }
    public onAreaChange(value: ((oldValue: Area, newValue: Area) => void) | undefined): this {
        this.getPeer().setOnAreaChange0Attribute(value);
        return this
    }
    public visibility(value: Visibility | undefined): this {
        this.getPeer().setVisibilityAttribute(value);
        return this
    }
    public flexGrow(value: number | undefined): this {
        this.getPeer().setFlexGrowAttribute(value);
        return this
    }
    public flexShrink(value: number | undefined): this {
        this.getPeer().setFlexShrinkAttribute(value);
        return this
    }
    public flexBasis(value: number | string | undefined): this {
        this.getPeer().setFlexBasisAttribute(value);
        return this
    }
    public alignSelf(value: ItemAlign | undefined): this {
        this.getPeer().setAlignSelfAttribute(value);
        return this
    }
    public displayPriority(value: number | undefined): this {
        this.getPeer().setDisplayPriorityAttribute(value);
        return this
    }
    public direction(value: Direction | undefined): this {
        this.getPeer().setDirectionAttribute(value);
        return this
    }
    public align(value: Alignment | undefined): this {
        this.getPeer().setAlignAttribute(value);
        return this
    }
    public position(value: Position | Edges | LocalizedEdges | undefined): this {
        this.getPeer().setPositionAttribute(value);
        return this
    }
    public markAnchor(value: Position | LocalizedPosition | undefined): this {
        this.getPeer().setMarkAnchorAttribute(value);
        return this
    }
    public offset(value: Position | Edges | LocalizedEdges | undefined): this {
        this.getPeer().setOffsetAttribute(value);
        return this
    }
    public enabled(value: boolean | undefined): this {
        this.getPeer().setEnabledAttribute(value);
        this.markDirty();
        return this
    }
    public alignRules(value: AlignRuleOption | undefined | LocalizedAlignRuleOptions | undefined): this {
        this.getPeer().setAlignRulesAttribute(value);
        return this
    }
    public aspectRatio(value: number | undefined): this {
        this.getPeer().setAspectRatioAttribute(value);
        return this
    }
    public clickEffect(value: ClickEffect | undefined): this {
        return this
    }
    public enableClickSoundEffect(value: boolean | undefined): this {
        this.getPeer()?.setEnableClickSoundEffectAttribute(value);
        return this
    }
    public onDragStart(value: ((event: DragEvent, extraParams?: string) => CustomBuilder | DragItemInfo) | undefined): this {
        this.getPeer()?.setOnDragStartAttribute(value);
        return this
    }
    public onDragEnter(value: ((event: DragEvent, extraParams?: string) => void) | undefined): this {
        this.getPeer()?.setOnDragEnterAttribute(value);
        return this
    }
    public onDragMove(value: ((event: DragEvent, extraParams?: string) => void) | undefined): this {
        this.getPeer()?.setOnDragMoveAttribute(value);
        return this
    }
    public onDragLeave(value: ((event: DragEvent, extraParams?: string) => void) | undefined): this {
        this.getPeer()?.setOnDragLeaveAttribute(value);
        return this
    }
    public onDrop(eventCallback: ((event: DragEvent, extraParams?: string) => void) | undefined | OnDragEventCallback | undefined): this {
        this.getPeer()?.setOnDrop0Attribute(eventCallback);
        return this
    }
    public onDrop(eventCallback: ((event: DragEvent, extraParams?: string) => void) | undefined | OnDragEventCallback | undefined, dropOptions: DropOptions): this {
        this.getPeer()?.setOnDrop1Attribute(eventCallback, dropOptions);
        return this
    }
    public onDragSpringLoading(callback_: ((value0: SpringLoadingContext) => void) | null | undefined, configuration?: DragSpringLoadingConfiguration): this {
        this.getPeer()?.setOnDragSpringLoadingAttribute(callback_, configuration)
        return this
    }
    public onDragEnd(value: ((event: DragEvent, extraParams?: string) => void) | undefined): this {
        this.getPeer()?.setOnDragEndAttribute(value);
        return this
    }
    public allowDrop(value: Array<UniformDataType> | null | Array<string> | undefined): this {
        hookAllowDrop(this, value);
        return this
    }
    public draggable(value: boolean | undefined): this {
        this.getPeer()?.setDraggableAttribute(value);
        return this
    }
    public dragPreview(preview: CustomBuilder | DragItemInfo | string | undefined, config?: PreviewConfiguration): this {
        this.getPeer()?.setDragPreviewAttribute(preview, config);
        return this
    }
    public onPreDrag(value: ((parameter: PreDragStatus) => void) | undefined): this {
        this.getPeer()?.setOnPreDragAttribute(value);
        return this
    }
    public linearGradient(value: LinearGradientOptions | undefined): this {
        return this
    }
    public sweepGradient(value: SweepGradientOptions | undefined): this {
        return this
    }
    public radialGradient(value: RadialGradientOptions | undefined): this {
        return this
    }
    public motionPath(value: MotionPathOptions | undefined): this {
        return this
    }
    public shadow(value: ShadowOptions | ShadowStyle | undefined): this {
        return this
    }
    public clip(value: boolean | undefined): this {
        return this
    }
    public clipShape(value: CircleShape | EllipseShape | PathShape | RectShape | undefined): this {
        return this
    }
    public mask(value: ProgressMask | undefined): this {
        return this
    }
    public maskShape(value: CircleShape | EllipseShape | PathShape | RectShape | undefined): this {
        return this
    }
    public key(value: string | undefined): this {
        this.getPeer().setKeyAttribute(value);
        return this
    }
    public id(value: string | undefined): this {
        this.getPeer().setIdAttribute(value);
        return this
    }
    public geometryTransition(id: string | undefined, options?: GeometryTransitionOptions): this {
        return this
    }
    public stateStyles(value: StateStyles | undefined): this {
        return this
    }
    public restoreId(value: int | undefined): this {
        this.getPeer().setRestoreIdAttribute(value);
        return this
    }
    public sphericalEffect(value: number | undefined): this {
        return this
    }
    public lightUpEffect(value: number | undefined): this {
        return this
    }
    public pixelStretchEffect(value: PixelStretchEffectOptions | undefined): this {
        return this
    }
    public accessibilityGroup(isGroup: boolean | undefined, accessibilityOptions?: AccessibilityOptions): this {
        return this
    }
    public accessibilityText(value: string | undefined | Resource | undefined): this {
        return this
    }
    public accessibilityNextFocusId(value: string | undefined): this {
        return this
    }
    public accessibilityDefaultFocus(value: boolean | undefined): this {
        return this
    }
    public accessibilityUseSamePage(value: AccessibilitySamePageMode | undefined): this {
        return this
    }
    public accessibilityScrollTriggerable(value: boolean | undefined): this {
        return this
    }
    public accessibilityRole(value: AccessibilityRoleType | undefined): this {
        return this
    }
    public onAccessibilityFocus(value: AccessibilityFocusCallback | undefined): this {
        return this
    }
    public accessibilityTextHint(value: string | undefined): this {
        return this
    }
    public accessibilityDescription(value: string | undefined | Resource | undefined): this {
        return this
    }
    public accessibilityLevel(value: string | undefined): this {
        return this
    }
    public accessibilityVirtualNode(value: CustomBuilder | undefined): this {
        return this
    }
    public accessibilityChecked(value: boolean | undefined): this {
        return this
    }
    public accessibilitySelected(value: boolean | undefined): this {
        return this
    }
    public obscured(value: Array<ObscuredReasons> | undefined): this {
        return this
    }
    public reuseId(value: string | undefined): this {
        return this
    }
    public reuse(value: ReuseOptions | undefined): this {
        return this
    }
    public renderFit(value: RenderFit | undefined): this {
        return this
    }
    public gestureModifier(value: GestureModifier | undefined): this {
        return this
    }
    public backgroundBrightness(value: BackgroundBrightnessOptions | undefined): this {
        return this
    }
    public onGestureJudgeBegin(value: ((gestureInfo: GestureInfo, event: BaseGestureEvent) => GestureJudgeResult) | undefined): this {
        this.getPeer().setOnGestureJudgeBeginAttribute(value);
        return this
    }
    public onGestureRecognizerJudgeBegin(callback_: GestureRecognizerJudgeBeginCallback | undefined, exposeInnerGesture?: boolean): this {
        this.getPeer().setOnGestureRecognizerJudgeBegin1Attribute(callback_, exposeInnerGesture);
        return this
    }
    public onGestureRecognizerJudgeBegin(callback_: GestureRecognizerJudgeBeginCallback | undefined): this {
        this.getPeer().setOnGestureRecognizerJudgeBegin0Attribute(callback_);
        return this
    }
    public shouldBuiltInRecognizerParallelWith(value: ShouldBuiltInRecognizerParallelWithCallback | undefined): this {
        this.getPeer().setShouldBuiltInRecognizerParallelWithAttribute(value);
        return this
    }
    public monopolizeEvents(value: boolean | undefined): this {
        this.getPeer().setMonopolizeEventsAttribute(value);
        return this
    }
    public onTouchIntercept(value: ((parameter: TouchEvent) => HitTestMode) | undefined): this {
        this.getPeer().setOnTouchInterceptAttribute(value);
        return this
    }
    public onSizeChange(value: SizeChangeCallback | undefined): this {
        this.getPeer().setOnSizeChangeAttribute(value);
        return this
    }
    public accessibilityFocusDrawLevel(value: FocusDrawLevel | undefined): this {
        return this
    }
    public customProperty(name: string, value: CustomProperty): this {
        hookCustomPropertyImpl(this, name, value);
        return this
    }
    public expandSafeArea(types?: Array<SafeAreaType> | undefined, edges?: Array<SafeAreaEdge> | undefined): this {
        return this
    }
    public background(content: CustomBuilder | ResourceColor | undefined, options?: BackgroundOptions): this {
        this.getPeer().setBackgroundAttribute(content);
        return this
    }
    public backgroundImage(value: ResourceStr | PixelMap | undefined): this {
        this.getPeer().setBackgroundImage0Attribute(value);
        return this
    }
    public backgroundImage(src: ResourceStr | PixelMap | undefined, options: BackgroundImageOptions): this {
        this.getPeer().setBackgroundImage1Attribute(src, options);
        return this
    }
    public backgroundImage(src: ResourceStr | PixelMap | undefined, repeat: ImageRepeat): this {
        this.getPeer().setBackgroundImage2Attribute(src, repeat);
        return this
    }
    public backgroundBlurStyle(style: BlurStyle | undefined, options?: BackgroundBlurStyleOptions, sysOptions?: SystemAdaptiveOptions): this {
        return this
    }
    public foregroundBlurStyle(style: BlurStyle | undefined, options?: ForegroundBlurStyleOptions, sysOptions?: SystemAdaptiveOptions): this {
        return this
    }
    public focusScopeId(id: string | undefined, isGroup?: boolean, arrowStepOut?: boolean): this {
        this.getPeer().setFocusScopeIdAttribute(id, isGroup, arrowStepOut);
        return this
    }
    public focusScopePriority(scopeId: string | undefined, priority?: FocusPriority): this {
        this.getPeer().setFocusScopePriorityAttribute(scopeId, priority);
        return this
    }
    public gesture(gesture: GestureType, mask?: GestureMask): this {
        return this
    }
    public priorityGesture(gesture: GestureType, mask?: GestureMask): this {
        return this
    }
    public parallelGesture(gesture: GestureType, mask?: GestureMask): this {
        return this
    }
    public blur(blurRadius: number | undefined, options?: BlurOptions, sysOptions?: SystemAdaptiveOptions): this {
        return this
    }
    public linearGradientBlur(value: number | undefined, options: LinearGradientBlurOptions | undefined): this {
        return this
    }
    public systemBarEffect(): this {
        return this
    }
    public backdropBlur(radius: number | undefined, options?: BlurOptions, sysOptions?: SystemAdaptiveOptions): this {
        return this
    }
    public sharedTransition(id: string | undefined, options?: sharedTransitionOptions): this {
        return this
    }
    public chainMode(direction: Axis | undefined, style: ChainStyle | undefined): this {
        return this
    }
    public dragPreviewOptions(value: DragPreviewOptions | undefined, options?: DragInteractionOptions): this {
        hookDragPreviewOptions(this, value, options)
        return this
    }
    public overlay(value: string | CustomBuilder | ComponentContent<Object> | undefined, options?: OverlayOptions): this {
        this.getPeer()?.setOverlayAttribute(value, options)
        return this
    }
    public blendMode(value: BlendMode | undefined, type?: BlendApplyType): this {
        return this
    }
    public advancedBlendMode(effect: BlendMode | BrightnessBlender | undefined, type?: BlendApplyType): this {
        return this
    }
    public bindTips(message: TipsMessageType | undefined, options?: TipsOptions): this {
        return this
    }
    public bindPopup(show: boolean | undefined, popup: PopupOptions | CustomPopupOptions | undefined): this {
        return this
    }
    public bindMenu(content: Array<MenuElement> | CustomBuilder | undefined, options?: MenuOptions | undefined): this {
        return this
    }
    public bindContextMenu(content: CustomBuilder | undefined, responseType: ResponseType | undefined, options?: ContextMenuOptions | undefined): this {
        return this
    }
    public bindContentCover(isShow: boolean | undefined | Bindable<boolean>, builder: CustomBuilder | undefined, type?: ModalTransition | ContentCoverOptions): this {
        return this
    }
    public bindSheet(isShow: boolean | undefined | Bindable<boolean>, builder: CustomBuilder | undefined, options?: SheetOptions): this {
        return this
    }
    public onVisibleAreaChange(ratios: Array<number> | undefined, event: VisibleAreaChangeCallback | undefined): this {
        return this
    }
    public onVisibleAreaApproximateChange(options: VisibleAreaEventOptions | undefined, event: VisibleAreaChangeCallback | undefined): this {
        this.getPeer().setOnVisibleAreaApproximateChangeAttribute(options, event);
        return this
    }
    public keyboardShortcut(value: string | FunctionKey | undefined, keys: Array<ModifierKey> | undefined, action?: (() => void)): this {
        this.getPeer().setKeyboardShortcutAttribute(value, keys,action);
        return this
    }
    width(value: Length | LayoutPolicy | undefined): this {
        if (value != null) {
            this.getPeer().setWidthAttribute(value as Length);
            this.markDirty();
        }
        return this;
    }
    height(value: Length | LayoutPolicy | undefined): this {
        if (value != null) {
            this.getPeer().setHeightAttribute(value as Length);
            this.markDirty();
        }
        return this;
    }
    backgroundColor(value: ResourceColor | undefined): this {
        if (value != null) {
            this.getPeer().setBackgroundColorAttribute(value as ResourceColor);
        }
        return this;
    }
    onClick(event: ((event: ClickEvent) => void) | undefined): this {
        this.getPeer().setOnClick0Attribute(event);
        return this;
    }
    zIndex(value: int | undefined): this {
        this.getPeer().setZIndexAttribute(value);
        return this;
    }
    size(value: SizeOptions | undefined): this {
        this.getPeer().setSizeAttribute(value);
        return this;
    }
}